; ---------------------------------------------------------------------------
; VRAM assignments for individual items and tile constants for graphics not
; used with PLCs. (Tile constants for PLC-loaded graphics are generated by
; the plcm macro.) 
; ---------------------------------------------------------------------------

; Common to 1p and 2p menus.
vram_StandardFont:             equ $0200

; Sega Screen
vram_SEGA:           		equ $0020
vram_IntroTrails:           equ $1000
tile_Nem_IntroTrails:		equ vram_IntroTrails/sizeof_cell
vram_Giant_Sonic:          	equ $1100

; Title Screen
vram_Title:                 equ $0000
vram_TitleSprites:          equ $2A00
tile_TitleSprites:			equ vram_TitleSprites/sizeof_cell
vram_MenuJunk:              equ $7E40
vram_Player1VS2:            equ $8040
vram_CreditsFont:           equ $A000
vram_StandardFont_TtlScr:	equ $D000

; Credits
vram_CreditText_CredScr:	equ $0020

; Menus
vram_MenuBox:               equ $0E00
vram_LevelSelectPics:       equ $1200

; 2P Results Screen
vram_1P2PWins:              equ $0E00
vram_SpecialPlayerVSPlayer: equ $7BE0
vram_2P_Signpost:           	equ $BD00
;vram_TwoPlayerResults:         equ $C000 ?

; Special Stage
vram_SpecialEmerald:		equ $2E80
vram_SpecialMessages:		equ $3440
vram_SpecialHUD:			equ $3F40
vram_SpecialHorizShadow:	equ $4780
vram_SpecialDiagShadow:		equ $4C40
vram_SpecialVertShadow:		equ $5380
vram_SpecialExplosion:		equ $56A0
vram_SpecialSonic:			equ $5CA0
vram_SpecialTails:			equ $6000
vram_SpecialTails_Tails:	equ $62C0
vram_SpecialRings:			equ $6440
vram_SpecialStart:			equ $7140
vram_SpecialBomb:			equ $7140
vram_SpecialStageResults:	equ $B200
vram_SpecialBack:			equ $E000
vram_SpecialStars:			equ $EFE0
vram_SpecialTailsText:		equ $F480

; Ending
vram_EndingCharacter:		equ $0320
vram_EndingFinalTornado:	equ $2AC0
vram_EndingPics:			equ $6500
vram_EndingMiniTornado:		equ $9260

; Continue Screen
vram_ContinueTails:          equ $A000
vram_ContinueText:           equ $A000
vram_ContinueText_2:         equ $A480
vram_MiniContinue:           equ $A480
vram_ContinueText_Additional:     equ $B200
vram_ContinueCountdown:             equ $DF80


; ---------------------------------------------------------------------------
; Universal locations.

tile_LevelArt:				equ $0000

; Animals.
vram_animal_1:              equ $B000
vram_animal_2:              equ $B280

; Game over.
vram_Game_Over:             equ $9BC0

; Titlecard.
vram_TitleCard:             equ $B000
ArtTile_LevelName:                     = $05DE

; End of level.
vram_Signpost:              equ $8680
ArtTile_HUD_Bonus_Score               = $0520
vram_Perfect:               equ $A800
vram_ResultsText:           equ $B600
ArtTile_ArtUnc_Signpost               = $05E8
vram_MiniCharacter:         equ $BE80
vram_Capsule:               equ $D000

; Tornado.
vram_Tornado:               equ $A000
vram_TornadoThruster:       equ $AC20
; Shared badniks and objects.


vram_Checkpoint:			equ $8F80
vram_TailsDust:				equ $9180
vram_SonicDust:				equ $9380
vram_TailsDrownNum:			equ vram_TailsDust
vram_SonicDrownNum:			equ vram_SonicDust
sizeof_CountdownNum:		equ sizeof_Art_Countdown/6	
vram_Numbers:				equ $9580
vram_Shield					equ $97C0
vram_Invinciblity_Stars:	equ $9BC0
vram_Monitors:				equ $D000
vram_Ring:					equ $D780
vram_HUD:					equ vram_Monitors+$940 ; $D940
vram_Sonic:					equ $F000
tile_Sonic:					equ vram_Sonic/sizeof_cell
vram_Tails:                 equ $F400
tile_Tails:					equ vram_Tails/sizeof_cell
vram_Tails_Tails:           equ $F600
tile_Tails_Tails:			equ vram_Tails_Tails/sizeof_cell

; ---------------------------------------------------------------------------
; HUD. The HUD components are linked in a chain, and linked to
; power-ups, because the mappings of monitors and lives counter(s)
; depend on one another. If you want to alter these (for example,
; because you need the VRAM for something else), you will probably
; have to edit the mappings (or move the power-ups and HUD as a
; single block unit).

;ArtTile_HUD_Score_E                   = vram_HUD + $18
;ArtTile_HUD_Score                     = ArtTile_HUD_Score_E + 2
;ArtTile_HUD_Rings                     = vram_HUD + $30
;ArtTile_HUD_Minutes                   = vram_HUD + $28
;ArtTile_HUD_Seconds                   = ArtTile_HUD_Minutes + 4
vram_Miles_Tails_1UP:        equ vram_HUD+$540			; $DE80
;ArtTile_ArtUnc_2p_life_counter_lives  = ArtTile_ArtUnc_2p_life_counter + 9
vram_lifecounter:				equ vram_HUD+$2140 ; $FA80
;vram_life_counter_lives     = vram_life_counter + 9

; Shared objects and badniks

; Objects that use the same art tiles on all levels in which
; they are loaded, even if not all levels load them.
vram_WaterSurface:           equ $8000
vram_Button:                 equ $8480
vram_HorizSpike:             equ $8580
vram_Spikes:                 equ $8680
vram_DignlSprng:             equ $8780
vram_LeverSpring:            equ $8800
vram_VrtclSprng:             equ $8B80
vram_HrzntlSprng:            equ $8E00

;		rsset	$8580
;vram_HorizSpike:             rs.b sizeof_Nem_HorizSpike
;vram_Spikes:                 rs.b sizeof_Nem_Spikes
;vram_DignlSprng:             rs.b sizeof_Nem_DignlSprng
;		rsset	$8800
;vram_LeverSpring:            rs.b sizeof_Nem_LeverSpring
;vram_VrtclSprng:             rs.b sizeof_Nem_VrtclSprng
;vram_HrzntlSprng:            rs.b sizeof_Nem_HrzntlSprng

; Some common objects loaded on all aquatic levels
vram_Explosion:              equ $B480
vram_Bubbles:                equ $BD00
vram_SuperSonic_stars:       equ $BE40

; EHZ, HTZ
;ArtTile_ArtKos_Checkers:               = ArtTile_ArtKos_LevelArt+$0158
;ArtTile_ArtUnc_Flowers1:               = $7280
;ArtTile_ArtUnc_Flowers2:               = $72C0
;ArtTile_ArtUnc_Flowers3:               = $7300
;ArtTile_ArtUnc_Flowers4:               = $7340
vram_Buzzer:                 	equ $7A40

; WFZ, SCZ
vram_WFZHrzntlPrpllr:        	equ $79A0
vram_Clouds:                	equ $A9E0
vram_WFZVrtclPrpllr:         	equ $AC20
vram_Balkriy:					equ $ACA0


; Level-specific objects and badniks.
; EHZ
vram_EHZPulseBall:				= $7380		; uncompressed
vram_Waterfall: 				equ $73C0
vram_Bridge:					equ $76C0
vram_Buzzer_Fireball:       	equ $77C0			; actually unused
vram_Coconuts:            		equ $7DC0
vram_Masher:               		equ $8280
ArtTile_ArtUnc_EHZMountains:	=	$A000			; uncompressed

; MTZ
vram_Shellcracker:          equ $6380
ArtTile_ArtUnc_Lava                   = $6800
ArtTile_ArtUnc_MTZCylinder            = $6980
ArtTile_ArtUnc_MTZAnimBack_1          = $6B80
ArtTile_ArtUnc_MTZAnimBack_2          = $6C40
vram_Asteron:           	equ $6D00
vram_Wheel:              equ $6F00
vram_WheelIndent:        equ $7E00
vram_LavaCup:               equ $7F20
vram_BoltEnd_Rope:          equ $7FA0
vram_SteamSpring:           equ $80A0
vram_SpikeBlock:          	equ $8280
vram_MTZSpike:              equ $8380
vram_Slicer:				equ $8780
vram_MTZAsstBlocks:         equ $A000
vram_LavaBubble:         	equ $A6C0
vram_Cog:                	equ $ABE0
vram_SpinTubeFlash:      equ $AD60

; WFZ
vram_Clucker:             	equ $6F20
vram_WFZTiltPlatforms:		equ $7260
vram_WFZVrtclLaser:         equ $73E0
vram_WFZWallTurret:         equ $7560
vram_WFZHrzntlLaser:        equ $7860
vram_WFZConveyorBeltWheel:  equ $7D40
vram_Hook:              	equ $7F40			; mappings for this object are bugged, this is worked around by adding 4 to the tile setting
vram_WFZBeltPlatform:       equ $81C0
vram_WFZGunPlatform:        equ $8340
vram_WFZUnusedBadnik:       equ $8A00
vram_WFZLaunchCatapult:     equ $8B80
vram_WFZSwitch:             equ $8C20
vram_WFZThrust:             equ $8CA0
vram_WFZFloatingPlatform:   equ $8DA0
vram_BreakPanels:           equ $9180

; SCZ
vram_Turtloid:              equ $7140
vram_Nebula:                equ $6DC0

; HTZ
vram_Rexon:                 equ $6FC0
vram_HTZFireball1:          equ $73C0
vram_HTZRock:               equ $7640
vram_SeeSaw:             	equ $78C0
vram_Sol:                   equ $7BC0
vram_HTZZipline:            equ $7CC0
vram_HTZFireball2:          equ $82C0
vram_HTZOneWayBarrier:      equ $84C0
ArtTile_ArtUnc_HTZMountains:        = $0500
ArtTile_ArtUnc_HTZClouds:              = ArtTile_ArtUnc_HTZMountains + $18
vram_Spiker:                equ $A400

; OOZ
ArtTile_ArtUnc_OOZPulseBall           = $02B6
ArtTile_ArtUnc_OOZSquareBall1         = $02BA
ArtTile_ArtUnc_OOZSquareBall2         = $02BE
ArtTile_ArtUnc_Oil1                   = $02C2
ArtTile_ArtUnc_Oil2                   = $02D2
vram_Burner:                equ $5C40
vram_OOZElevator:           equ $5E80
vram_SlidingSpikes:         equ $6180
vram_BurnerLid:             equ $6580
vram_StripedBlocksVert:     equ $6640
vram_Oilfall:               equ $66C0
vram_Oilfall2:              equ $68C0
vram_SpringBall:          	equ $6A80
vram_LaunchBall:            equ $6D00
vram_OOZPlatform:           equ $73A0
vram_PushSpring:            equ $78A0
vram_OOZSwingPlat:          equ $7C60
vram_StripedBlocksHoriz:    equ $7FE0
vram_Fan:           		equ $8060
vram_Aquis:                 equ $A000
vram_Octus:                 equ $A700

; MCZ
vram_Flasher:               equ $7500
vram_Crawlton:              equ $7800
vram_Crate:                 equ $7A80
vram_MCZCollapsingPlat:     equ $7E80
vram_VineSwitch:            equ $81C0
vram_VinePulley:            equ $83C0
vram_DrawbridgeLogs:        equ $8780

; CNZ
vram_Crawl:                 equ $6800
vram_LargeMovingBlock:     	equ $6D80
vram_SnakePlats:   			equ $6F80
vram_BombPenalty:         	equ $7000
vram_CNZElevator:           equ $7080
vram_Cage:               	equ $7100
vram_HexBumper:           	equ $7280
vram_RoundBumper:        	equ $7340
vram_Flipper:             	equ $7640
vram_SaucerBumper:       	equ $7CC0
vram_DiagLauncher:       	equ $8040
vram_VertLauncher:       	equ $8440

; Specific to 1p CNZ
ArtTile_ArtUnc_CNZFlipTiles_1         = $0330
ArtTile_ArtUnc_CNZFlipTiles_2         = $0540
vram_SlotPics_1:         	equ $AA00
vram_SlotPics_2:          	equ $AC00
vram_SlotPics_3:         	equ $AE00
sizeof_SlotPic:				equ sizeof_art_cnzslotpics/6 ; size of each individual slot pic in bytes

; Specific to 2p CNZ
ArtTile_ArtUnc_CNZFlipTiles_1_2p      = $0330
ArtTile_ArtUnc_CNZFlipTiles_2_2p      = $0740
vram_SlotPics_1_2p:       	equ $EA00
vram_SlotPics_2_2p:      	equ $EC00
vram_SlotPics_3_2p:       	equ $EE00

; CPZ
ArtTile_ArtUnc_CPZAnimBack            = $0370
vram_Pylon:         		equ $6E60
vram_CPZConstructionStripes:	equ $7280
vram_Booster:				equ $7380
vram_CPZElevator:           equ $7400
vram_CPZDumpingPipePlat:    equ $7600
vram_CPZTubeSpring:         equ $7C00
vram_StairBlock:         equ $8300
vram_CPZMetalBlock:         equ $8600
vram_Droplet:            equ $8780
vram_Grabber:               equ $A000
vram_Spiny:                 equ $A5A0

; DEZ
ArtTile_ArtUnc_DEZAnimBack            = $0326
vram_DEZConstructionStripes:  equ $6500

; ARZ
vram_ARZBarrier:        	equ $7F00
vram_Leaves:                equ $8200
vram_ArrowAndShooter:       equ $82E0
vram_Waterfall3:			equ	$8500
tile_Waterfall3:			equ	vram_Waterfall3/sizeof_cell
ArtTile_ArtUnc_Waterfall2:             = $042C
ArtTile_ArtUnc_Waterfall1_1:           = $0430
vram_Whisp:                 equ $A000
vram_Grounder:              equ $A120
vram_ChopChop:              equ $A760
ArtTile_ArtUnc_Waterfall1_2:           = $AAE0
vram_BubbleGenerator:       equ $AB60

; ---------------------------------------------------------------------------
; Bosses
; Common tiles for some bosses (any for which no eggpod tiles are defined,
; except for WFZ and DEZ bosses).
vram_Eggpod_common:               equ $A000
; Common tiles for all bosses.
vram_FieryExplosion:        equ $B000

; CPZ boss
vram_CPZEggpodJets:  		equ $8300
vram_CPZEggpod:     		equ $8400
vram_CPZBoss:               equ $A000
vram_CPZBossSmoke:          equ $AE00

; EHZ boss
vram_EHZEggpod:             equ $7400
vram_EHZBoss:     			equ $8000
vram_EggChopperBlades:		equ $AD80

; HTZ boss
vram_HTZEggpod:             equ $7820
vram_HTZBoss:               equ $8420
vram_HTZBossSmoke:          equ $BC80

; ARZ boss
vram_ARZBoss:               equ $7C00

; MCZ boss
vram_MCZBoss:               equ $7800
vram_FallingRocks:          equ $AC00

; CNZ boss
vram_CNZBoss:               equ $80E0
;vram_CNZBoss_Fudge:         equ vram_CNZBoss-$C00		; $74E0, badly reused mappings... 

; MTZ boss
vram_MTZBoss:               equ $6F80
vram_MTZEggpodJets:         equ $AC00

; OOZ boss
vram_OOZBoss:               equ $7180

; WFZ and DEZ
vram_RobotnikUpper:         equ $A000
vram_RobotnikRunning:       equ $A300
vram_RobotnikLower:         equ $AC80

; WFZ boss
vram_WFZBoss:               equ $6F20

; DEZ
vram_DEZBoss:               equ $6600
vram_DEZWindow:   			equ $6F00
vram_MechaSonic:            equ $7000

; Tile counts for several levels, used to patch tiles

ArtTile_ArtKos_LevelArt               = $0000
ArtTile_ArtKos_NumTiles_EHZ           = $0393
ArtTile_ArtKos_NumTiles_CPZ           = $0364
ArtTile_ArtKos_NumTiles_ARZ           = $03F6
ArtTile_ArtKos_NumTiles_CNZ           = $0331
ArtTile_ArtKos_NumTiles_HTZ_Main      = $01FC			; Until this tile, equal to EHZ tiles.
ArtTile_ArtKos_NumTiles_HTZ_Sup       = $0183			; Overwrites several EHZ tiles.
ArtTile_ArtKos_NumTiles_HTZ           = ArtTile_ArtKos_NumTiles_HTZ_Main + ArtTile_ArtKos_NumTiles_HTZ_Sup - 1
ArtTile_ArtKos_NumTiles_MCZ           = $03A9
ArtTile_ArtKos_NumTiles_OOZ           = $02AA
ArtTile_ArtKos_NumTiles_MTZ           = $0319
ArtTile_ArtKos_NumTiles_SCZ           = $036E
ArtTile_ArtKos_NumTiles_WFZ_Main      = $0307			; Until this tile, equal to SCZ tiles.
ArtTile_ArtKos_NumTiles_WFZ_Sup       = $0073			; Overwrites several SCZ tiles.
ArtTile_ArtKos_NumTiles_WFZ           = ArtTile_ArtKos_NumTiles_WFZ_Main + ArtTile_ArtKos_NumTiles_WFZ_Sup - 1
ArtTile_ArtKos_NumTiles_DEZ           = $0326			; Skips several CPZ tiles.


; ---------------------------------------------------------------------------
; Unused beta leftovers
; ---------------------------------------------------------------------------

vram_HPZPulseOrb_1:       			equ $5D00
vram_HPZPulseOrb_2:      			equ $5E00
vram_HPZPulseOrb_3:       			equ $5F00
vram_HiddenPalaceBridge:						equ $6000
vram_HPZWaterfall:       			equ $62A0
vram_HPZPlatform:           		equ $6940
vram_HiddenPalaceOrb:             			equ $6B40
vram_HPZEmerald:         			equ $7240
vram_Unknown:             			equ $7F40
vram_FloatPlatform:       			equ $8300


; ---------------------------------------------------------------------------
; Unused Sonic 1 leftovers
; ---------------------------------------------------------------------------

vram_MZPlatform:					equ $5700
vram_SpikePole:						equ $7300
vram_GiantRing:                		equ $8000
vram_GiantRingFlash:          		equ $8C40
vram_Bonus:				            equ $96C0
vram_SmashWall:			            equ $B200
vram_PurpleRock:        			equ $D800

vram_S1Credits:						equ $B400
vram_S1Title_Credits:				equ $6000


; VRAM assignments for animals in 
; Sonic 1 ending sequence
vram_Flicky_End:            equ $B4A0
vram_Rabbit_End            	equ $AA60
vram_Penguin_End:           equ $AE60
vram_Seal_End:              equ $B0A0
vram_Pig_End:               equ $B260
vram_Chicken_End:           equ $ACA0
vram_Squirrel_End:          equ $B660
